name: flutter_integration_actions
description: A new Flutter module

publish_to: 'none' 

version: 1.0.3+4

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  generate: true

  
  module:
    androidX: true
    androidPackage: com.flutter.module.example
