name: CI

on: [push, workflow_dispatch]

jobs:
  flutter_job:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.3'
      - name: Run setup script
        run: ./setup_flutter_as_app.sh

      - name: Run Flutter tests
        run: flutter test

      - name: Setup Android Emulator
        uses: reactivecircus/android-emulator-runner@v2.28.0
        with:
          api-level: 31
          target: google_apis
          profile: tv_1080p
          arch: x86_64
          script: ./install_app_flutter_job.sh

  android_native_job:
    needs: flutter_job
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Run setup script
        run: ./setup_flutter_as_app.sh

      - name: Build Android App
        run: |
          cd ./android_native_app
          ./gradlew assembleRelease

      - name: Setup Android Emulator
        uses: reactivecircus/android-emulator-runner@v2.28.0
        with:
          api-level: 31
          target: google_apis
          profile: tv_1080p
          arch: x86_64
          script: ./install_app_android_job.sh
